### ISSUE TITLE
Support Debian packaging

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1422]
This is an epic ticket to hold all the tech debt and/or stuff we'd like to get fixed up to support Debian packaging alongside RHEL. If an item has an associated ticket to it, it should be shown here.

- [ ] run e2e tests against deb packages
- [ ] standard directory location for passenger (bin, libs, location.ini)
- [ ] standard directory location for nginx
- [ ] seamless, easy way to get the version
- [ ] template sudoer file
- [ ] fixup debian config files. There has to be a `.rpmnew` equivalent where we don't just blindly overwrite files.

I figure a decent roadmap is to get the `feature/deb-packaing` based off of or merged with master, supporting e2e tests. Then, we can fix stuff up and coalesce some of these things like common directory structures.

**Comment by treydock** [comment]
From #1239  also need to be able to sign the packages with either GPG key or whatever apt uses.
