### ISSUE TITLE
Feature parity port of Files app

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#713]
This issue is to track porting the Files app to Ruby integrated into the dashboard app.

Port should have feature parity along with these enhancements:

- [ ] Display file owner instead of UID https://github.com/OSC/ondemand/issues/572
- [ ] Show last modification date+time instead of just date https://github.com/OSC/ondemand/issues/594
- [ ] sortable by column (size, modified date, name, etc.) [#271](https://github.com/OSC/ondemand/issues/271)
- [ ] admin-pinned shortcuts (formerly called favorites) on the left side (replacing the tree)
- [ ] proper logging of all user actions that change state
- [ ] handle long directory file paths using dropdowns for part of the path (similar to how Box handles it)

Copy/move will use the same mechanism as existed before (click copy move to copy references to a "cart" stored in local storage, and then navigate to the directory to you want the files to be copied to/moved to, and click copy to or move to on the "cart". The big difference is we display the contents of this "~~clipboard~~ moveboard" and on copy/move the progress may be displayed in a modal.

All configuration for the Files app under /etc/ood/config/files should still affect this app.

This quick port will provide a base for making more substantial changes to the UI as well as extending it to support cloud storage.

**Comment by ericfranz** [comment]
https://github.com/OSC/ondemand/pull/1043 and https://github.com/OSC/ondemand/pull/1040 were the final PRs
